#!/usr/bin/env python
"""Render every consumer of the Noah brand mark from the canonical SVGs.

This is the ONLY place icon outputs are produced. Inputs:
  • brand/noah-icon.svg          (bare symbol, transparent corners)
  • brand/noah-icon-plated.svg   (same symbol on rounded white plate)

Outputs are written to:
  • Website (onnoah.app/public/)     — bare SVG copies
  • Desktop public/                  — bare PNG copies (splash + favicon)
  • Desktop src/assets/              — bare SVG copy (used by NoahIcon.tsx)
  • Desktop src-tauri/icons/         — plated PNG/.icns/.ico variants
                                       (dock, taskbar, iOS, Android)

Any other place rendering an icon is a bug — file a fix and add it here.
Run via brand/sync.sh, which also regenerates the source SVGs first.
"""
from __future__ import annotations

import io
import os
import pathlib
import shutil
import subprocess
import sys

import cairosvg
from PIL import Image


HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
BARE_SVG = HERE / "noah-icon.svg"
PLATED_SVG = HERE / "noah-icon-plated.svg"

# Targets — adjust the ONNOAH path via env if the sibling repo lives elsewhere.
ONNOAH_PUBLIC = pathlib.Path(os.environ.get("ONNOAH_PUBLIC", REPO.parent / "onnoah.app/public"))
DESKTOP = REPO / "apps/desktop"
TAURI_ICONS = DESKTOP / "src-tauri/icons"

WARN = "<!-- AUTO-GENERATED by brand/sync.sh — DO NOT EDIT. Source: noah/brand/build.py -->"


def _copy_svg_with_warning(src: pathlib.Path, dest: pathlib.Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    body = src.read_text()
    dest.write_text(f"{WARN}\n{body}")
    print(f"  → {dest}")


def _render_png(src: pathlib.Path, size: int, dest: pathlib.Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    cairosvg.svg2png(url=str(src), output_width=size, output_height=size, write_to=str(dest))
    print(f"  → {dest} ({size}×{size})")


def _delete_if_exists(p: pathlib.Path) -> None:
    if p.exists():
        p.unlink()
        print(f"  ✗ removed legacy {p}")


def step_website() -> None:
    print("[website] bare SVG → favicon.svg + noah-icon.svg")
    if not ONNOAH_PUBLIC.is_dir():
        print(f"  ! {ONNOAH_PUBLIC} not found — skipping website copy.")
        return
    _copy_svg_with_warning(BARE_SVG, ONNOAH_PUBLIC / "favicon.svg")
    _copy_svg_with_warning(BARE_SVG, ONNOAH_PUBLIC / "noah-icon.svg")


def step_desktop_public() -> None:
    """The Tauri webview's HTML splash + favicon. Both consume the PLATED
    PNG — the self-contained near-black tile reads on both the dark and
    the light splash background (a bare near-white wrench would vanish on
    the light theme). The HTML applies its own border-radius on top.
    """
    print("[desktop/public] plated PNG → icon-32.png + noah-icon.png")
    pub = DESKTOP / "public"
    _render_png(PLATED_SVG, 32, pub / "icon-32.png")
    _render_png(PLATED_SVG, 256, pub / "noah-icon.png")


def step_desktop_assets() -> None:
    """src/assets/noah-icon.svg is imported by NoahIcon.tsx (the in-app
    logo chip). It gets the PLATED tile so the mark is theme-independent —
    the same near-black app-icon chip in both light and dark mode. We also
    remove the legacy PNG so it can't be re-imported.
    """
    print("[desktop/src/assets] plated SVG → noah-icon.svg (delete legacy PNG)")
    assets = DESKTOP / "src/assets"
    _copy_svg_with_warning(PLATED_SVG, assets / "noah-icon.svg")
    _delete_if_exists(assets / "noah-icon.png")


def step_tauri_source() -> None:
    """The src-tauri/icons/ regen script reads source-aurora.svg. Write
    the plated SVG to that path so the rest of step_tauri_icons can render
    consistent plated variants.
    """
    print("[desktop/src-tauri] plated SVG → source-aurora.svg")
    _copy_svg_with_warning(PLATED_SVG, TAURI_ICONS / "source-aurora.svg")


# Desktop dock / Linux / Tauri main icons. All rendered from plated.
_DESKTOP_PNGS: list[tuple[int, str]] = [
    (1024, "icon.png"),
    (32,   "32x32.png"),
    (64,   "64x64.png"),
    (128,  "128x128.png"),
    (256,  "128x128@2x.png"),
]

# Windows Store tile + StoreLogo (plated; Windows uses these directly).
_WINDOWS_STORE: list[tuple[int, str]] = [
    (30,  "Square30x30Logo.png"),
    (44,  "Square44x44Logo.png"),
    (71,  "Square71x71Logo.png"),
    (89,  "Square89x89Logo.png"),
    (107, "Square107x107Logo.png"),
    (142, "Square142x142Logo.png"),
    (150, "Square150x150Logo.png"),
    (284, "Square284x284Logo.png"),
    (310, "Square310x310Logo.png"),
    (50,  "StoreLogo.png"),
]

# iOS — exact dimensions match the original Tauri output so the Xcode
# project's asset catalog doesn't need to change.
_IOS_ICONS: list[tuple[int, str]] = [
    (20,   "ios/AppIcon-20x20@1x.png"),
    (40,   "ios/AppIcon-20x20@2x.png"),
    (40,   "ios/AppIcon-20x20@2x-1.png"),
    (60,   "ios/AppIcon-20x20@3x.png"),
    (29,   "ios/AppIcon-29x29@1x.png"),
    (58,   "ios/AppIcon-29x29@2x.png"),
    (58,   "ios/AppIcon-29x29@2x-1.png"),
    (87,   "ios/AppIcon-29x29@3x.png"),
    (40,   "ios/AppIcon-40x40@1x.png"),
    (80,   "ios/AppIcon-40x40@2x.png"),
    (80,   "ios/AppIcon-40x40@2x-1.png"),
    (120,  "ios/AppIcon-40x40@3x.png"),
    (120,  "ios/AppIcon-60x60@2x.png"),
    (180,  "ios/AppIcon-60x60@3x.png"),
    (76,   "ios/AppIcon-76x76@1x.png"),
    (152,  "ios/AppIcon-76x76@2x.png"),
    (167,  "ios/AppIcon-83.5x83.5@2x.png"),
    (1024, "ios/AppIcon-512@2x.png"),
]

# Android — ic_launcher and ic_launcher_round get plated rendering;
# ic_launcher_foreground gets the BARE symbol so Android's adaptive
# icon mask + background layer can compose the final dock appearance.
_ANDROID_PLATED: list[tuple[int, str]] = [
    (48,  "android/mipmap-mdpi/ic_launcher.png"),
    (48,  "android/mipmap-mdpi/ic_launcher_round.png"),
    (49,  "android/mipmap-hdpi/ic_launcher.png"),
    (49,  "android/mipmap-hdpi/ic_launcher_round.png"),
    (96,  "android/mipmap-xhdpi/ic_launcher.png"),
    (96,  "android/mipmap-xhdpi/ic_launcher_round.png"),
    (144, "android/mipmap-xxhdpi/ic_launcher.png"),
    (144, "android/mipmap-xxhdpi/ic_launcher_round.png"),
    (192, "android/mipmap-xxxhdpi/ic_launcher.png"),
    (192, "android/mipmap-xxxhdpi/ic_launcher_round.png"),
]
_ANDROID_BARE: list[tuple[int, str]] = [
    (108, "android/mipmap-mdpi/ic_launcher_foreground.png"),
    (162, "android/mipmap-hdpi/ic_launcher_foreground.png"),
    (216, "android/mipmap-xhdpi/ic_launcher_foreground.png"),
    (324, "android/mipmap-xxhdpi/ic_launcher_foreground.png"),
    (432, "android/mipmap-xxxhdpi/ic_launcher_foreground.png"),
]


def step_tauri_icons() -> None:
    print("[desktop/src-tauri/icons] all plated variants from plated SVG")
    for size, name in _DESKTOP_PNGS + _WINDOWS_STORE + _IOS_ICONS + _ANDROID_PLATED:
        _render_png(PLATED_SVG, size, TAURI_ICONS / name)
    print("[desktop/src-tauri/icons] adaptive-foreground variants from bare SVG")
    for size, name in _ANDROID_BARE:
        _render_png(BARE_SVG, size, TAURI_ICONS / name)


def step_tauri_ico() -> None:
    print("[desktop/src-tauri/icons] icon.ico (multi-resolution from plated)")
    ico_path = TAURI_ICONS / "icon.ico"
    sizes = [16, 32, 48, 256]
    images = []
    for s in sizes:
        buf = io.BytesIO()
        cairosvg.svg2png(url=str(PLATED_SVG), output_width=s, output_height=s, write_to=buf)
        buf.seek(0)
        images.append(Image.open(buf).convert("RGBA"))
    images[0].save(ico_path, format="ICO", sizes=[(s, s) for s in sizes], append_images=images[1:])
    print(f"  → {ico_path}")


def step_tauri_icns() -> None:
    print("[desktop/src-tauri/icons] icon.icns (built via iconutil from plated)")
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        iconset = pathlib.Path(td) / "icon.iconset"
        iconset.mkdir()
        for s in (16, 32, 64, 128, 256, 512, 1024):
            _render_png(PLATED_SVG, s, iconset / f"icon_{s}x{s}.png")
        # @2x retina pairs.
        for s in (16, 32, 128, 256, 512):
            s2 = s * 2
            src = iconset / f"icon_{s2}x{s2}.png"
            if src.exists():
                shutil.copy(src, iconset / f"icon_{s}x{s}@2x.png")
        subprocess.run(
            ["iconutil", "-c", "icns", "-o", str(TAURI_ICONS / "icon.icns"), str(iconset)],
            check=True,
        )
    print(f"  → {TAURI_ICONS / 'icon.icns'}")


def main() -> int:
    if not BARE_SVG.exists() or not PLATED_SVG.exists():
        print(f"ERROR: canonical SVGs missing in {HERE} — run build.py first.", file=sys.stderr)
        return 1
    step_website()
    step_desktop_public()
    step_desktop_assets()
    step_tauri_source()
    step_tauri_icons()
    step_tauri_ico()
    step_tauri_icns()
    print("\nDone. Every consumer of the Noah brand mark has been refreshed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
